// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gacha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GachaServiceClient is the client API for GachaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaServiceClient interface {
	GachaDraw(ctx context.Context, in *GachaDrawRequest, opts ...grpc.CallOption) (*GachaDrawResponse, error)
}

type gachaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaServiceClient(cc grpc.ClientConnInterface) GachaServiceClient {
	return &gachaServiceClient{cc}
}

func (c *gachaServiceClient) GachaDraw(ctx context.Context, in *GachaDrawRequest, opts ...grpc.CallOption) (*GachaDrawResponse, error) {
	out := new(GachaDrawResponse)
	err := c.cc.Invoke(ctx, "/user.GachaService/GachaDraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaServiceServer is the server API for GachaService service.
// All implementations must embed UnimplementedGachaServiceServer
// for forward compatibility
type GachaServiceServer interface {
	GachaDraw(context.Context, *GachaDrawRequest) (*GachaDrawResponse, error)
	// mustEmbedUnimplementedGachaServiceServer()
}

// UnimplementedGachaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGachaServiceServer struct {
}

func (UnimplementedGachaServiceServer) GachaDraw(context.Context, *GachaDrawRequest) (*GachaDrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GachaDraw not implemented")
}
func (UnimplementedGachaServiceServer) mustEmbedUnimplementedGachaServiceServer() {}

// UnsafeGachaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaServiceServer will
// result in compilation errors.
type UnsafeGachaServiceServer interface {
	mustEmbedUnimplementedGachaServiceServer()
}

func RegisterGachaServiceServer(s grpc.ServiceRegistrar, srv GachaServiceServer) {
	s.RegisterService(&GachaService_ServiceDesc, srv)
}

func _GachaService_GachaDraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GachaDrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaServiceServer).GachaDraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.GachaService/GachaDraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaServiceServer).GachaDraw(ctx, req.(*GachaDrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaService_ServiceDesc is the grpc.ServiceDesc for GachaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.GachaService",
	HandlerType: (*GachaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GachaDraw",
			Handler:    _GachaService_GachaDraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gacha.proto",
}
